version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      # This gets the local Docker service started
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build \
              --tag ${CIRCLE_PROJECT_REPONAME} \
              .
      - run:
          name: Start Docker container
          command: |
            docker run \
                --interactive \
                --tty \
                --detach \
                --name ${CIRCLE_PROJECT_REPONAME} \
                ${CIRCLE_PROJECT_REPONAME}
            docker ps
      - run:
          name: Run tests
          command: |
            docker exec -it ${CIRCLE_PROJECT_REPONAME} sh bin/run-all.sh
      - run:
          name: Stop Docker container
          command: |
            docker stop ${CIRCLE_PROJECT_REPONAME}
